apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service-frontend-deployment
  labels:
    app: edge-service-frontend-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service-frontend-server
  template:
    metadata:
      labels:
        app: edge-service-frontend-server
    spec:
      containers:
        - name: edge-service-frontend-server
          image: inspectionedgehub/edge-service-frontend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              resources:
                limits:
                  cpu: 0.2
                  memory: "200Mi"
              env:
                - name: SAFETY_EDGE_SERVICE_BASEURL
                  value: "safety-edge-service-server:8050"

---
apiVersion: v1
kind: Service
metadata:
  name: edge-service-frontend-server
  labels:
    app: edge-service-frontend-server
spec:
  type: NodePort
  selector:
    app: edge-service-frontend-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
